# Generated by Django 3.2.25 on 2026-09-20 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof'), ('ff', 'Poular'), ('sr', 'Sérère')], default='fr', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_fr', models.TextField()),
                ('question_wo', models.TextField(blank=True, null=True)),
                ('question_ff', models.TextField(blank=True, null=True)),
                ('question_sr', models.TextField(blank=True, null=True)),
                ('answer_fr', models.TextField()),
                ('answer_wo', models.TextField(blank=True, null=True)),
                ('answer_ff', models.TextField(blank=True, null=True)),
                ('answer_sr', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('general', 'Général'), ('alerts', 'Alertes'), ('parcels', 'Parcelles'), ('harvests', 'Récoltes'), ('market', 'Marché'), ('account', 'Compte')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'question_fr'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('bot', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('language', models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof'), ('ff', 'Poular'), ('sr', 'Sérère')], default='fr', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
