# Generated by Django 3.2.25 on 2026-09-04 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=160)),
                ('buyer_phone', models.CharField(max_length=30)),
                ('crop', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Classe A', 'Classe A')], max_length=30)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField()),
                ('buyer_type', models.CharField(choices=[('Grossiste', 'Grossiste'), ('Restaurant', 'Restaurant'), ('Transformateur', 'Transformateur'), ('Distributeur', 'Distributeur')], default='Grossiste', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_needs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=160)),
                ('farmer_phone', models.CharField(max_length=30)),
                ('crop', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Classe A', 'Classe A')], max_length=30)),
                ('available_date', models.DateField()),
                ('price_indicative', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reserved', 'Réservée'), ('closed', 'Clôturée')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('opened', 'Ouverte'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('closed', 'Clôturée')], default='opened', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_market_negotiations', to=settings.AUTH_USER_MODEL)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='agriculture.marketneed')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='agriculture.marketoffer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='marketnegotiation',
            constraint=models.UniqueConstraint(fields=('offer', 'need'), name='unique_market_negotiation_pair'),
        ),
    ]
