# Generated by Django 4.2.7 on 2026-09-14 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agriculture", "0002_auto_20260904_1311"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="photo_analyses/")),
                ("etat_apparent", models.TextField()),
                ("anomalies", models.JSONField(default=list)),
                ("maturite", models.CharField(max_length=100)),
                ("qualite", models.CharField(max_length=100)),
                ("prescription", models.TextField()),
                ("confiance", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parcelle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_analyses",
                        to="agriculture.parcelle",
                    ),
                ),
                (
                    "proprietaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse photo",
                "verbose_name_plural": "Analyses photos",
                "ordering": ["-created_at"],
            },
        ),
    ]
