# Generated by Django 3.2.25 on 2026-10-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0003_photoanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='id_externe',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='VenteHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vente', models.CharField(max_length=50, unique=True)),
                ('date_vente', models.DateField()),
                ('recolte_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendu_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invendu_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_historiques', to='agriculture.parcelle')),
            ],
            options={
                'verbose_name': 'Vente historique',
                'verbose_name_plural': 'Ventes historiques',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='MesureSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('volume_eau_m3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('humidite_sol_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capteur_id', models.CharField(max_length=100)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_sol', to='agriculture.parcelle')),
            ],
            options={
                'verbose_name': 'Mesure du sol',
                'verbose_name_plural': 'Mesures du sol',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DonneeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_production', models.CharField(max_length=50, unique=True)),
                ('date_production', models.DateField()),
                ('rendement_estime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_recolte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('couts_production', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions_dataset', to='agriculture.parcelle')),
            ],
            options={
                'verbose_name': 'Donnée de production',
                'verbose_name_plural': 'Données de production',
                'ordering': ['-date_production'],
            },
        ),
        migrations.AddIndex(
            model_name='mesuresol',
            index=models.Index(fields=['parcelle', '-timestamp'], name='mesure_parcelle_time_idx'),
        ),
    ]
