# Generated by Django 3.2.25 on 2026-10-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0004_auto_20261007_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='culture_dataset',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='date_plantation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='type_sol',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
