# Generated by Django 3.2.25 on 2026-10-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0005_auto_20261007_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_culture', models.CharField(max_length=50, unique=True)),
                ('nom_culture', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('saison', models.CharField(max_length=100)),
                ('duree_cycle_jours', models.PositiveIntegerField()),
                ('rendement_moyen_t_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('besoin_eau_mm_cycle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_parcelle_dataset', models.CharField(blank=True, default='', max_length=50)),
                ('id_producteur_dataset', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Culture du dataset',
                'verbose_name_plural': 'Cultures du dataset',
                'ordering': ['id_culture'],
            },
        ),
        migrations.AddIndex(
            model_name='culturedataset',
            index=models.Index(fields=['id_parcelle_dataset'], name='culture_parcelle_idx'),
        ),
        migrations.AddIndex(
            model_name='culturedataset',
            index=models.Index(fields=['id_producteur_dataset'], name='culture_producteur_idx'),
        ),
    ]
