# Generated by Django 3.2.25 on 2026-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0006_auto_20261007_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='est_demo',
            field=models.BooleanField(default=False),
        ),
    ]
